services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.40
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: notify
      MYSQL_ROOT_PASSWORD: qwe123
    volumes:
      - ./storage/dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redisdata:/data
    restart: always

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_PORT=11211
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db
